export type ReportTemplateType = 'executive' | 'technical' | 'compliance'

export interface TemplateData {
  reportName: string
  reportType: ReportTemplateType
  generatedAt: string
  totalFindings: number
  totalAssets: number
  totalPages: number
  criticalCount: number
  highCount: number
  mediumCount: number
  lowCount: number
  topFindings: { title: string; severity: string; target: string }[]
  summaryText: string
  assetBreakdown: { label: string; count: number }[]
  complianceScore?: number
}

export interface ReportTemplate {
  id: string
  name: string
  type: ReportTemplateType
  description: string
  render: (data: TemplateData) => string
  preview: (data: TemplateData) => string
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;')
}

function severityBadge(s: string): string {
  const colors: Record<string, string> = { critical: '#dc2626', high: '#ea580c', medium: '#ca8a04', low: '#16a34a' }
  const escaped = escapeHtml(s)
  return `<span style="background:${colors[s]||'#666'};color:#000;padding:1px 6px;font-size:9px;font-weight:900;letter-spacing:0.15em;text-transform:uppercase">${escaped}</span>`
}

const executiveTemplate: ReportTemplate = {
  id: 'executive-summary',
  name: 'Executive Summary',
  type: 'executive',
  description: 'High-level overview for stakeholders with risk posture and key metrics',
  render(data: TemplateData): string {
    return `# Executive Briefing — ${data.reportName}

## Risk Posture Overview

- **Total Findings:** ${data.totalFindings}
- **Critical:** ${data.criticalCount} | **High:** ${data.highCount} | **Medium:** ${data.mediumCount} | **Low:** ${data.lowCount}
- **Assets Assessed:** ${data.totalAssets}
- **Report Generated:** ${data.generatedAt}

## Executive Summary

${data.summaryText}

## Critical & High Priority Findings

| Severity | Title | Target |
|----------|-------|--------|
${data.topFindings.filter(f => f.severity === 'critical' || f.severity === 'high').map(f => `| ${f.severity} | ${f.title} | ${f.target} |`).join('\n')}

## Asset Coverage

${data.assetBreakdown.map(a => `- **${a.label}:** ${a.count}`).join('\n')}

${data.complianceScore !== undefined ? `## Compliance Score\n\n**${data.complianceScore}/100** — ${data.complianceScore >= 80 ? 'Passing' : data.complianceScore >= 50 ? 'Needs improvement' : 'Failing'}\n` : ''}

---
*Generated by SecuScan Executive Template*
`
  },
  preview(data: TemplateData): string {
    const pct = data.totalFindings > 0 ? Math.round((data.criticalCount + data.highCount) / data.totalFindings * 100) : 0
    return `<div style="font-family:monospace;background:#1a1a1a;color:#e0e0e0;padding:16px;border:2px solid #333">
      <div style="font-size:10px;font-weight:900;text-transform:uppercase;letter-spacing:0.2em;color:#888;margin-bottom:12px">Executive Preview</div>
      <div style="font-size:13px;font-weight:900;margin-bottom:8px">${escapeHtml(data.reportName)}</div>
      <div style="display:flex;gap:12px;margin-bottom:12px">
        <span style="background:#222;padding:4px 8px;font-size:9px">Critical ${data.criticalCount}</span>
        <span style="background:#222;padding:4px 8px;font-size:9px">High ${data.highCount}</span>
        <span style="background:#222;padding:4px 8px;font-size:9px">Medium ${data.mediumCount}</span>
      </div>
      <div style="font-size:9px;color:#888;text-transform:uppercase;letter-spacing:0.1em">${pct}% of findings are critical/high severity — ${data.totalAssets} assets assessed</div>
    </div>`
  },
}

const technicalTemplate: ReportTemplate = {
  id: 'technical-deep-dive',
  name: 'Technical Deep Dive',
  type: 'technical',
  description: 'Detailed findings report for security engineers with full technical context',
  render(data: TemplateData): string {
    return `# Technical Report — ${data.reportName}

## Scan Metadata

- **Generated:** ${data.generatedAt}
- **Assets Scanned:** ${data.totalAssets}
- **Total Findings:** ${data.totalFindings}

## Finding Severity Distribution

| Severity | Count |
|----------|-------|
| Critical | ${data.criticalCount} |
| High     | ${data.highCount} |
| Medium   | ${data.mediumCount} |
| Low      | ${data.lowCount} |

## All Findings

${data.topFindings.map((f, i) => `${i + 1}. [${f.severity.toUpperCase()}] ${f.title} — ${f.target}`).join('\n')}

## Technical Summary

${data.summaryText}

## Asset Inventory

${data.assetBreakdown.map(a => `| ${a.label} | ${a.count} |`).join('\n')}

---
*Generated by SecuScan Technical Template*
`
  },
  preview(data: TemplateData): string {
    const previewFindings = data.topFindings.slice(0, 3).map(f =>
      `▸ [${severityBadge(f.severity)}] ${escapeHtml(f.title)}`
    ).join('<br>')
    return `<div style="font-family:monospace;background:#1a1a1a;color:#e0e0e0;padding:16px;border:2px solid #333">
      <div style="font-size:10px;font-weight:900;text-transform:uppercase;letter-spacing:0.2em;color:#888;margin-bottom:12px">Technical Preview</div>
      <div style="font-size:13px;font-weight:900;margin-bottom:8px">${escapeHtml(data.reportName)}</div>
      <div style="font-size:9px;color:#aaa;margin-bottom:8px">${data.totalFindings} findings across ${data.totalAssets} assets</div>
      <div style="font-size:9px;font-family:monospace;color:#666">${previewFindings}</div>
    </div>`
  },
}

const complianceTemplate: ReportTemplate = {
  id: 'compliance-audit',
  name: 'Compliance Audit',
  type: 'compliance',
  description: 'Regulatory compliance report with control mapping and gap analysis',
  render(data: TemplateData): string {
    const score = data.complianceScore ?? 0
    return `# Compliance Report — ${data.reportName}

## Compliance Score

**Overall:** ${score}/100
**Status:** ${score >= 80 ? 'PASS' : score >= 50 ? 'REVIEW' : 'FAIL'}

## Control Gaps

${data.topFindings.filter(f => f.severity === 'critical' || f.severity === 'high').map(f => `- **${f.title}** (${f.target}) — Severity: ${f.severity.toUpperCase()}`).join('\n') || 'No critical or high-severity gaps identified.'}

## Asset Compliance Coverage

| Asset Type | Count |
|------------|-------|
${data.assetBreakdown.map(a => `| ${a.label} | ${a.count} |`).join('\n')}

## Summary

${data.summaryText}

## Key Metrics

- Total Findings: ${data.totalFindings}
- Critical: ${data.criticalCount}
- High: ${data.highCount}
- Medium: ${data.mediumCount}
- Low: ${data.lowCount}
- Assets: ${data.totalAssets}

---
*Generated by SecuScan Compliance Template*
`
  },
  preview(data: TemplateData): string {
    const score = data.complianceScore ?? 0
    const color = score >= 80 ? '#16a34a' : score >= 50 ? '#ca8a04' : '#dc2626'
    return `<div style="font-family:monospace;background:#1a1a1a;color:#e0e0e0;padding:16px;border:2px solid #333">
      <div style="font-size:10px;font-weight:900;text-transform:uppercase;letter-spacing:0.2em;color:#888;margin-bottom:12px">Compliance Preview</div>
      <div style="font-size:13px;font-weight:900;margin-bottom:8px">${escapeHtml(data.reportName)}</div>
      <div style="font-size:24px;font-weight:900;color:${color};margin-bottom:8px">${score}/100</div>
      <div style="font-size:9px;color:#888;text-transform:uppercase;letter-spacing:0.1em">${data.criticalCount + data.highCount} control gaps identified</div>
    </div>`
  },
}

const builtInTemplates: ReportTemplate[] = [executiveTemplate, technicalTemplate, complianceTemplate]

export function getTemplates(type?: ReportTemplateType): ReportTemplate[] {
  if (type) return builtInTemplates.filter(t => t.type === type)
  return builtInTemplates
}

export function getTemplateById(id: string): ReportTemplate | undefined {
  return builtInTemplates.find(t => t.id === id)
}

export function renderTemplate(template: ReportTemplate, data: TemplateData): string {
  return template.render(data)
}

export function renderPreview(template: ReportTemplate, data: TemplateData): string {
  return template.preview(data)
}

export function exportAsFile(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename.endsWith('.md') ? filename : `${filename}.md`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function buildTemplateData(report: {
  name: string
  type: ReportTemplateType
  generated_at: string
  findings: number
  assets: number
  pages: number
}, summary?: {
  critical_findings?: number
  high_findings?: number
  medium_findings?: number
  low_findings?: number
  total_findings?: number
  total_assets?: number
}): TemplateData {
  return {
    reportName: report.name,
    reportType: report.type,
    generatedAt: report.generated_at,
    totalFindings: report.findings,
    totalAssets: report.assets,
    totalPages: report.pages,
    criticalCount: summary?.critical_findings ?? 0,
    highCount: summary?.high_findings ?? 0,
    mediumCount: summary?.medium_findings ?? 0,
    lowCount: summary?.low_findings ?? 0,
    topFindings: [],
    summaryText: `Report of type "${report.type}" containing ${report.findings} findings across ${report.assets} assets.`,
    assetBreakdown: [{ label: 'Total Assets', count: report.assets }],
  }
}
